services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    tty: true
    command: tail -f /dev/null
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: makara-project
        target: /src/makara-project
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql

volumes:
  mysql: